runtime: nodejs18
env: standard

env_variables:
  MONGODB_URI: "mongodb+srv://Reyan:reyan1122@cluster0.ym1qsw1.mongodb.net/organic_orchard?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "luxury-dry-fruits-super-secret-jwt-key-2025"
  RESEND_API_KEY: "re_CZJmq6NC_M7FiSAomFxYqDzU7soS6EKLG"
  NODE_ENV: "production"
